### ISSUE TITLE
Cannot specify NWB file at command line

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#1]
Minor issue: when attempting to open the GUI at the command line by providing a file path string, the user is still prompted to choose a file. Works fine once you select a file in the GUI.

For specificity, here is the exact command:
`python ecog_vis.py '/path/to/data/EC125_B22.nwb'`

**Comment by luiztauffer** [comment]
@jrliu95 thank you for pointing that out.
Just corrected it, it should be working now!
