### ISSUE TITLE
Saving on NWB files - two sets of files

### ISSUE THREAD

**Issue by luiztauffer** [luiztauffer/ecogVIS#10]
Two sets of files in different folders: one with *Raw ElectricalSeries & Preprocessed DecompositionSeries*, and one with *High gamma ElectricalSeries*. Both files would have the same behavioral info (time intervals if we get that saved into the file, trial info, electrode info). We could copy the general subject file into both folders maybe to make the linking easier. The benefit to this is 1) if people want to copy files to their local computer, they don't need to copy all the raw/decomp as well and 2) there's enough people that only look at the high gamma, so it's worth replicating the current setup (a raw folder and a high gamma folder for each subject)

**Comment by luiztauffer** [comment]
@jrliu95 and @bendichter
do you have suggestions for default file names in both directories?

**Comment by bendichter** [comment]
EC125_B22_hg

**Comment by luiztauffer** [comment]
7f752195a6db45069aee086e644b2604035bd32b
