### ISSUE TITLE
Reorganization caused slight break? Unable to start GUI

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#12]
I think the recent reorganization of some of the code has caused a break. So there is now an `ecogvis` folder inside of `ecogVis` and the Python script to call is inside the `ecogvis` folder. When I try to call that script, I get the error:

```
Traceback (most recent call last):
  File "ecogvis/ecogvis.py", line 15, in <module>
    from ecogvis.functions.subFunctions import ecogVIS
  File "/Users/jessieliu/ChangLab/projects/ecogVIS/ecogvis/ecogvis.py", line 15, in <module>
    from ecogvis.functions.subFunctions import ecogVIS
ModuleNotFoundError: No module named 'ecogvis.functions'; 'ecogvis' is not a package
```

I completely removed my previous environment and deleted the repo, and re-installed everything and ran into this issue.

**Comment by luiztauffer** [comment]
@jrliu95 how are you starting the GUI?
Could you try importing as a module and let me know if the problem persists?

```python
from ecogvis.ecogvis import main

fname = '/path_to/EC125_B22.nwb'
main(fname)
```

**Comment by jrliu95** [comment]
Oh, okay, yes I was running it from the command line. All works now! Is it a permanent change to not have it at the command line? May not really matter because eventually I'll be making a custom command for everyone to call from the command line that activates the environment and opens the GUI for them.

**Comment by luiztauffer** [comment]
I think it's actually better like this, since you call from command line an user-written file such as the one above, or one that accepts arguments form command line as well, and ecogvis remains as a standard python module. What do you think? I'll close it for now, but you can re-open it in any case.

**Comment by jrliu95** [comment]
Yeah, I think you're right. And I'll just write a custom command anyways so it's good to keep it as a module.
