### ISSUE TITLE
Preprocess button with options

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#13]
In the "Preprocess" button can you add a box to be able to specify what number channel CAR to use?

Additionally, if the preprocessed data already exists, is there a way to display in this box what those preprocessing options had been set to? For example, printing out there that the preprocessed data exists and then saying what sampling rate, notch filter, and CAR were used? I guess these would have to be written into the file somewhere. Let me know what you think

**Comment by luiztauffer** [comment]
done

**Comment by jrliu95** [comment]
When I press the preprocess button, the dialog box doesn't pop up?

**Comment by luiztauffer** [comment]
@jrliu95 that's supposed to be working. Do you get any errors, or what happens?

**Comment by jrliu95** [comment]
@luiztauffer Nothing happens on the GUI side when I click the button, but this error message comes up in my terminal.

![Screen Shot 2019-06-24 at 6 23 58 PM](https://user-images.githubusercontent.com/17503400/60063336-75b9cf00-96b1-11e9-8f7b-02f32b2a317f.png)

**Comment by luiztauffer** [comment]
Can you try it with a raw file? (only raw signals, no preprocessed)

**Comment by jrliu95** [comment]
Yep, works now! I really like the check boxes also, thanks for adding those.
