### ISSUE TITLE
High Gamma Button

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#19]
Now the high gamma button works for me.

Can you make the default name option for saving to a separate file be 'ECX_BY_hg.nwb'?

I also like how there's the option to add more bands. Can you make it the option to add both a custom band (which is what there is now), but also to add a band from the typical Chang Lab bands? Like, the preprocessing should be done on bands up to 200Hz. Some people in the lab use 70-200 Hz for high gamma so it'd be super nice to be able to just select (maybe like checkboxes) those extra couple bands above 150Hz.

**Comment by luiztauffer** [comment]
For some reason we have assumed before that the default was 70~150 Hz.
I changes it now to 70~200 Hz

**Comment by jrliu95** [comment]
Indeed the default should be 70-150Hz (this is the classic definition of high gamma). All I was saying is to have the option to add bands that are already defined.

Currently, if you want to add a new band to the high gamma calculation, you have to enter the center and sigma frequencies yourself. So I'd like there to be the other pre-defined bands (as defined in https://github.com/luiztauffer/process_ecog/blob/docker/ecog/utils/bands.py), available.

As a specific example, I'd imagine you click the High Gamma button and you want to create a new high gamma file. The default bands 70-150 Hz are already selected, and greyed out are the other Chang Lab frequency bands. Perhaps each band has a checkbox next to them? So if I wanted to then include up to 200Hz, I could just select those extra few bands. Let me know if that make sense!

**Comment by luiztauffer** [comment]
The changes are in place, let me know if that's what you had in mind!

**Comment by jrliu95** [comment]
The dialog box looks great, this is exactly what I had in mind!

However, when I try to make the new file, I get this error:

![Screen Shot 2019-06-26 at 6 04 23 PM](https://user-images.githubusercontent.com/17503400/60225757-053fb900-983d-11e9-8448-22fe3d08d4b2.png)

We previously discussed that invalid times have to be stored as a separate .csv file. Do you know why it needs to reference this table? In the new nwb file that I'm working off of, there is no invalid times table. I could make an empty one if need be.

**Comment by luiztauffer** [comment]
Oops, I should be testing for the existence of this group (and other things, I just came to realize). Thanks for pointing that out!

**Comment by luiztauffer** [comment]
Ok, I corrected for this and some other fields present in the files @bendichter provided me with.
The main problem we're having now is when creating new files, but preserving fields from another file without being connected to them. This is an open Issue at https://github.com/NeurodataWithoutBorders/pynwb/issues/668
The current implementation should work temporarily, but it's important to note that's not the best way and we should change it to use the option `link_data=False` once it's working on pyNWB.

**Comment by jrliu95** [comment]
Ah, okay. The high gamma button works properly now for me. So is it linking the data right now? That is, the relative paths must be maintained between the new high gamma file and the original raw file?

**Comment by luiztauffer** [comment]
No, the way it's done right now there's no link. You can move your files around and test it! Let me know if anything is failing

**Comment by jrliu95** [comment]
Okay, so right now, everything gets copied into the new files? Having the raw+preprocessed files and the high gamma files be independent is, I think, our goal? Do you think there's a reason for it not to be? Perhaps I'm not grasping what you mean exactly, by how this isn't the best way to do this.

**Comment by luiztauffer** [comment]
The way it is implemented right now, you have two options:
1 - High Gamma is saved in current file (the one with raw/preprocessed)
2 - High Gamma is saved in a new file, of user's choice. In this file, some other data will be copied as well, such as electrodes, lab name, stimulus... but not 'raw' or 'preprocessed' data. This new file should work independently of the original file.

**Comment by jrliu95** [comment]
Right, and option 2 is what I envision most people doing. Thanks for clarifying!
