### ISSUE TITLE
Quick move between block files

### ISSUE THREAD

**Issue by luiztauffer** [luiztauffer/ecogVIS#20]
@jrliu95
I figured this could be an interesting option, to have a quick move between blocks of the same subject. This takes away space, though, that could possibly be taken by more important action buttons for you guys. Let me know what you think.

![screenshot_blocks](https://user-images.githubusercontent.com/24541631/59978279-138e9a80-95db-11e9-9cb0-5163cdcb203c.png)

**Comment by jrliu95** [comment]
That's a great idea! Since people processing the blocks likely want to process quite a few of them, this will be very useful. Is this in the newest version of the GUI?

**Comment by luiztauffer** [comment]
it's in place now!
