### ISSUE TITLE
initial dialog

### ISSUE THREAD

**Issue by bendichter** [luiztauffer/ecogVIS#22]
The initial dialog is confusing. It asks for the session name and then says "e.g. your_name". Why are you asking for the session name? Can't you get that from the file? And it looks like you are asking for *my* name (Ben).

**Comment by luiztauffer** [comment]
The session name can be the user name or any other name the user wants to associate with the item he/she will include and save. This is related to #15

**Comment by luiztauffer** [comment]
You can, of course, just press enter and leave it blank

**Comment by luiztauffer** [comment]
@bendichter can I close this?
