### ISSUE TITLE
Indentation error in subDialogs

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#23]
There's an indentation error in the `check_hg_exists` function in `subDialogs.py`. It's unclear what the `else` is referring to, could you fix this?

https://github.com/luiztauffer/ecogVIS/blob/aa85e6088fdb06bbdf4b325d4684d9c08ed9fc8a/ecogvis/functions/subDialogs.py#L485

Thanks!

**Comment by luiztauffer** [comment]
Do you get indentation error on this part? 
I commented the condition for this specific `else` for clarity!

**Comment by jrliu95** [comment]
It seems to not give the error anymore, thanks!
