### ISSUE TITLE
Power vs Absolute value in spectral decomp of data

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#24]
I just noticed that the spectral decomposition is being saved as the bandpower (V**2/Hz), but only the absolute value is being taken (not being squared). Is that still giving out the bandpower or just absolute value of the analytic signal? Maybe @bendichter needs to weigh in on this, or I can ask around.

https://github.com/luiztauffer/ecogVIS/blob/aa85e6088fdb06bbdf4b325d4684d9c08ed9fc8a/ecogvis/signal_processing/processing_data.py#L348

**Comment by bendichter** [comment]
Yeah, if it's taking the absolute value then it is analytic amplitude, not power

**Comment by luiztauffer** [comment]
Thanks for pointing that error!
How would you prefer it to be saved, the amplitude or the amplitude squared?

**Comment by jrliu95** [comment]
The amplitude, so I think all you need to do is change the name/units
